# Generated by Django 5.0 on 2024-01-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_operational', models.BooleanField(default=True)),
                ('is_busy', models.BooleanField(default=False)),
                ('current_floor', models.IntegerField(default=1)),
                ('direction', models.CharField(default='UP', max_length=5)),
            ],
        ),
    ]
