# Generated by Django 5.0 on 2024-01-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
